apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana_grupoa2
  namespace: logging_grupoa2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
  #         image: docker.elastic.co/kibana/kibana:8.12.2
   #Tenemos que crear imagen
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: https://elasticsearch:9200
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: ELASTIC_PASSWORD
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: none

---

apiVersion: v1
kind: Service
metadata:
  name: kibana_grupoa2
  namespace: logging_grupoa2
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30502