apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch_grupoa2
  namespace: logging_grupoa2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: ELASTIC_PASSWORD
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.keystore.path
              value: certs/http.p12
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
            - name: certs
              mountPath: /usr/share/elasticsearch/config/certs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc-grupoa2
        - name: certs
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging_grupoa2
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200