apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-grupoa2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/elasticsearch

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc-grupoa2
  namespace: logging_grupoa2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi