apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-waf
  namespace: grupoa2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-waf
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.paths: /var/log/apache2/*.log        
        co.elastic.logs/module: apache
        co.elastic.logs.fileset.access.enabled: "true"
        co.elastic.logs.fileset.error.enabled: "true"
        co.elastic.logs/processors.add_fields.fields.service: apache-waf
        co.elastic.logs/processors.add_fields.fields.env: grupoa2
      labels:
        app: apache-waf
        env: grupoa2
    spec:
      containers:
        - name: apache-waf
          ports:
            - containerPort: 80
          image: victoralejos/pepsapachewaf:1.3

---
apiVersion: v1
kind: Service
metadata:
  name: apache-waf
  namespace: grupoa2
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30602
  selector:
    app: apache-waf
